services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./echo-tell:/var/www/html"
    depends_on:
      - mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 

    restart: unless-stopped


  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./echo-tell:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - "./docker/volume/mysql:/var/lib/mysql"

